import type { Metadata } from "next";
import { Playfair, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const playfair = Playfair({
  subsets: ["latin"],
  variable: "--font-playfair",
});
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plusJakartaSans",
});

export const metadata: Metadata = {
  title: "satuwaktu.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={`${playfair.variable} ${plusJakartaSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
